SKIPUNZIP=1
unzip -qjo "$ZIPFILE" -x 'META-INF' 'customize.sh' -d $MODPATH >&2

ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print "   Disable Safe Media Volume"
ui_print "   by Vetheon @ Lyrinox Technologies"
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""
ui_print "  Patching audio props..."
ui_print "  Disabling CSD enforcement..."
ui_print "  Clearing safe volume state..."
ui_print ""
ui_print "  ✓ Done!"
ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""
ui_print "  If this module helped you,"
ui_print "  consider sponsoring us on GitHub!"
ui_print ""
ui_print "  github.com/sponsors/LyrinoxTechnologies"
ui_print ""
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print ""
